# Generated by Django 5.2.5 on 2025-08-08 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('harga_normal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('harga_promo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('value_selling', models.CharField(help_text='Keunggulan/USP produk', max_length=255)),
                ('deskripsi', models.TextField()),
                ('value_isi_buket', models.TextField(help_text='Isi buket / item-item dalam produk')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produks', to='main_admin.kategori')),
            ],
        ),
        migrations.CreateModel(
            name='GambarProduk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='produk/')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gambar_list', to='main_admin.produk')),
            ],
        ),
    ]
