# Generated by Django 5.2.5 on 2025-08-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='deskripsi',
            field=models.TextField(default='tidak Ada deskripsi'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='value_isi_buket',
            field=models.TextField(default='-', help_text='Isi buket / item-item dalam produk'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='value_selling',
            field=models.CharField(default='-', help_text='Keunggulan/USP produk', max_length=255),
        ),
    ]
