# Generated by Django 5.2.5 on 2025-08-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0002_alter_produk_deskripsi_alter_produk_value_isi_buket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produk',
            name='value_isi_buket',
            field=models.TextField(blank=True, help_text='Isi buket / item-item dalam produk', null=True),
        ),
        migrations.AlterField(
            model_name='produk',
            name='value_selling',
            field=models.CharField(blank=True, help_text='Keunggulan/USP produk', max_length=255, null=True),
        ),
    ]
