# Generated by Django 5.2.5 on 2025-08-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0003_alter_produk_deskripsi_alter_produk_value_isi_buket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='jumlah_dilihat',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
