# Generated by Django 5.2.5 on 2025-09-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0004_produk_jumlah_dilihat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='harga_normal',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='produk',
            name='harga_promo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
