# Generated by Django 5.2.5 on 2025-09-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0005_alter_produk_harga_normal_alter_produk_harga_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='harga_normal',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='produk',
            name='harga_promo',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True),
        ),
    ]
